feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      circuitBreaker:
        errorThresholdPercentage: 50
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 10000
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
service-product:
  ribbon:
    ConnectTimeout: 2000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 0
    OkToRetryOnAllOperatins: true
    ReadTimeout: 2000
spring:
  application:
    name: service-order
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true
  rabbitmq:
    addresses: 10.7.173.71:5672
    connection-timeout: 10000
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    username: guest
    virtual-host: /
